Reject requests with no username
When a request comes in with no username, an exception is thrown:

```
AttributeError at /
'NoneType' object has no attribute 'strip'
```

A correct LDAP user always needs a username,
so we can reject any request that has no username.